//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTable
    {
        public int DishID { get; set; }
        public string Dish { get; set; }
        public string Cuisine { get; set; }
        public string MainIngredients { get; set; }
        public string Post { get; set; }
        public string Author { get; set; }
        public int AuthorID { get; set; }
        public string Date { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
